// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fanyfgijgaotmykhjnxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbnlmZ2lqZ2FvdG15a2hqbnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTEwMzEsImV4cCI6MjA3MzI2NzAzMX0.0LX4Pu7Kd726K3espSh_iqv3f6LHFROnGmLM9uVVuuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});